name: "Velocity - env-destroy-action"
description: "Destroys an environment in Velocity using Github Actions."
author: "Velocity"
inputs:
  velocity-token:
    required: true
    description: "veloctl authentication token"
  name:
    required: true
    description: "the environment name"
  use-gh-deployments:
    required: true
    description: "use Github Deployments API"
    default: "true"
  version:
    required: false
    description: "specific veloctl version (default: latest)"
    default: "latest"
runs:
  using: "node12"
  main: "dist/index.js"
